export { default as LandingPage } from './LandingPage'
export { default as About } from './About'
export { default as Highlights } from './Highlights' 
export { default as Events } from './Events'
export { default as Reservation } from './Reservation'