export { default as LandingPage } from './LandingPage'
export { default as About } from './About'
export { default as Highlights } from './Highlights' 
export { default as Events } from './Events'
export { default as Reservation } from './Reservation'
export { default as Footer } from './Footer'
export { default as Booking } from './Booking'